[package]
name = "rsecure"
version = "0.3.0"
edition = "2024"
authors = ["containerscrew info@containerscrew.com"]
rust-version = "1.90.0"
description = "A simple file encryption and decryption tool using AES-GCM."
repository = "https://github.com/containerscrew/rsecure"
license-file = "LICENSE"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5.56", features = ["derive"] }
anyhow = "1.0.71"
walkdir = "2.3.3"
colored = "3.1.1"

[profile.release]
strip = "debuginfo"
